export { default as Home } from './Home'
export { default as About } from './About'
export { default as Stack } from './Stack'
export { default as Portfolio } from './Portfolio'
export { default as Contact } from './Contact'